
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      database: postgresql
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
      database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  kafka:
    bootstrap-servers: kafka-service:9092
    topics:
      - like
      - comments
      - reply
    consumer:
      group-id: group-1
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

jwt:
  secret: ${JWT_SECRET}

cloud:
  aws:
    s3:
      bucket: way-bucket-s3
      path:
        daily_image: daily_image
        history_body: history_body
        history_thumbnail: history_thumbnail
        history_image: history_image
        ai_text: ai_text
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
server:
  port: 8080

springdoc:
  api-docs:
    path: /post-service/v3/api-docs
  swagger-ui:
    path: /post-service/swagger-ui.html

config:
  feign:
    member-url: http://apis.way-blog.today/member-service