name: WAY-post
run-name: WAY post
on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Qemu
      uses: docker/setup-qemu-action@v2

    - name: Login KakaoCloud
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.PROJECT_NAME }}.kr-central-2.kcr.dev
        username: ${{ secrets.ACCESS_KEY }}
        password: ${{ secrets.ACCESS_SECRET_KEY }}

    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
  
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build -x test --no-daemon --console=plain

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        file: Dockerfile
        context: .
        push: true
        tags: ${{ secrets.PROJECT_NAME }}.kr-central-2.kcr.dev/${{ secrets.REPOSITORY_NAME }}/way-post:${{ github.sha }}

  update-deployment-file:
    
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
    - name: Checkout argo-manifest repository
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.USERNAME }}/argo-manifest
        token: ${{ secrets.PAT }}

    - name: Install yq
      run: sudo snap install yq

    - name: Update image in rollout file
      run: |
        yq e '.spec.template.spec.containers[0].image = "${{ secrets.PROJECT_NAME }}.kr-central-2.kcr.dev/${{ secrets.REPOSITORY_NAME }}/way-post:${{ github.sha }}"' ./post/way-be-postservice-rollout.yaml -i 
    - name: Commit and Push changes
      
      run: |
        git config --global user.email "${{ secrets.EMAIL }}"
        git config --global user.name "${{ secrets.USERNAME }}"
        git add .
        git commit -m "Update way-be-postservice-rollout.yaml"
        git remote set-url origin https://${{ secrets.PAT }}@github.com/${{ secrets.USERNAME }}/argo-manifest
        git push --set-upstream origin HEAD